version: '3.4'

services:
  weaviate:
    image: semitechnologies/weaviate:1.23.10
    ports:
      - "8080:8080"
      - "50051:50051"
    restart: unless-stopped
    environment:
      ENABLE_MODULES: text2vec-transformers
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://transformers:8080
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      
    depends_on:
      - transformers

  transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      ENABLE_CUDA: "0"  # change to "1" if running with GPU

volumes:
  weaviate_data:
